# Generated by Django 3.0.4 on 2020-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200330_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('one', 'Category 1'), ('two', 'Category 2'), ('three', 'Category 3')], default=1, max_length=256),
            preserve_default=False,
        ),
    ]
