# Generated by Django 3.0.4 on 2020-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('two', 'Category 2'), ('one', 'Category 1'), ('three', 'Category 3')], max_length=256),
        ),
    ]
