# Generated by Django 3.0.4 on 2020-03-30 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200330_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_edited',
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('two', 'Category 2'), ('three', 'Category 3'), ('one', 'Category 1')], max_length=256),
        ),
    ]
