# Generated by Django 3.0.4 on 2020-03-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200330_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('one', 'Category 1'), ('three', 'Category 3'), ('two', 'Category 2')], max_length=256),
        ),
    ]
