# Generated by Django 3.0.4 on 2020-03-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200330_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('two', 'Category 2'), ('three', 'Category 3'), ('one', 'Category 1')], max_length=256),
        ),
    ]
