# Generated by Django 3.0.4 on 2020-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200330_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('three', 'Category 3'), ('two', 'Category 2'), ('one', 'Category 1')], max_length=256),
        ),
    ]
