# Generated by Django 3.0.4 on 2020-03-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200330_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3')], max_length=30),
        ),
    ]
