# Generated by Django 3.0.4 on 2020-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200401_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Category 1', 'Category 1'), ('Category 2', 'Category 2')], max_length=30),
        ),
    ]
