# Generated by Django 3.0.4 on 2020-04-09 11:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200408_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
