# Generated by Django 3.0.4 on 2020-04-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['sent_on']},
        ),
    ]
