# Generated by Django 3.0.4 on 2020-04-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
